#connect the client to AD using ldap backend
---
  - name: Install dependencies.
    apt:
      name: "{{ packages }}"
    vars:
      packages:
       - realmd
       - libpam-mount
       - cifs-utils
       - sssd-tools
       - sssd
       - libnss-sss
       - libpam-sss
       - adcli
       - packagekit
       - nss-updatedb

  - name: Check if there is a keytab.
    stat:
      path: "/root/ldap.keytab"
    register: keytab

  - name: Zoom karpeta sortu.
    file:
      path: /root/zoom
      state: directory

  #sss_obfuscate -d <domain_name>
  - name: Configure sssd with LDAP.
    template:
      src: "{{ role_path }}/templates/etc/sssd/sssd_ldap.j2"
      dest: "/etc/sssd/sssd.conf"
      mode: 0600
    register: sssd
    when: keytab.stat.exists == False

  - name: Configure sssd with kerberos.
    template:
      src: "{{ role_path }}/templates/etc/sssd/sssd_ad.j2"
      dest: "/etc/sssd/sssd.conf"
      mode: 0600
    register: sssd
    when: keytab.stat.exists == True

  - name: Copy ldap keytab.
    copy:
      src: "/root/ldap.keytab"
      dest: "/etc/krb5.keytab"
      mode: 0600
    when: keytab.stat.exists == True

  - name: Create home dir at login.
    replace:
      dest: /usr/share/pam-configs/mkhomedir
      regexp: 'Default: no'
      replace: 'Default: yes'
    register: mkhomedir

  - name: Update pam configuration.
    command: pam-auth-update --package --enable mkhomedir
    args:
    when: (sssd.changed  == true) or (mkhomedir.changed == true)
