#!/bin/sh
if [ $# -eq 0 ]
  then
    echo "You have to choose a disk"
    lsblk | grep disk
    exit
fi
for n in /dev/$1* ; do umount $n ; done
swapoff --all
dd if=/dev/zero of=/dev/$1 bs=10240 count=1
parted -s /dev/$1 mklabel gpt  \
 mkpart primary fat32 0% 200MB  \
 mkpart primary ext4 200MB 10GB  \
 mkpart primary linux-swap 10GB 14GB  \
 mkpart primary ext4 14GB 100%  \
 set 1 legacy_boot on
mkfs.vfat /dev/${1}1 -F 32 -n BOOT
mkfs.ext4 /dev/${1}2 -FL system
mkswap /dev/${1}3
mkfs.ext4 /dev/${1}4 -FL home
dd bs=440 count=1 conv=notrunc if=/usr/lib/syslinux/mbr/gptmbr.bin of=/dev/$1
syslinux --install /dev/${1}1
mkdir sda1
mount /dev/${1}1 sda1
cp syslinux_local.cfg sda1/syslinux.cfg
cp /boot/ipxe.lkrn sda1/
cp /usr/lib/syslinux/modules/bios/libutil.c32 sda1/
cp /usr/lib/syslinux/modules/bios/menu.c32 sda1/
cp /usr/lib/syslinux/modules/bios/ldlinux.c32 sda1/
mkdir sda2
mount /dev/${1}2 sda2
echo "copying the image..."
pv /lib/live/mount/medium/live/filesystem.squashfs > sda2/filesystem.squashfs
cd sda2
echo "installing on disk..."
unsquashfs filesystem.squashfs
cd ..
mv sda2/squashfs-root/* sda2/
rmdir sda2/squashfs-root
rm sda2/filesystem.squashfs
echo "updating fstab..."
echo "/dev/${1}1        /boot           vfat    defaults                0 0" > sda2/etc/fstab
echo "/dev/${1}2    /                   ext4    defaults                0 0" >> sda2/etc/fstab
echo "/dev/${1}3    swap        swap    defaults                0 0" >> sda2/etc/fstab
echo "/dev/${1}4    /home       ext4    defaults                0 0" >> sda2/etc/fstab
echo "copying kernel and initrd"
if test -f "sda2/initrd.img"; then
    cp sda2/initrd.img sda1/
    cp sda2/vmlinuz sda1/
fi
if test -f "sda2/boot/initrd.img"; then
    cp sda2/boot/initrd.img sda1/ 
    cp sda2/boot/vmlinuz sda1/
fi
echo "removing unmute"
rm sda2/etc/xdg/autostart/unmute.desktop
echo "restoring NetworkManager"
if test -f "sda2/usr/share/applications/nm-applet.desktop"; then
    cp sda2/usr/share/applications/nm-applet.desktop sda2/etc/xdg/autostart/nm-applet.desktop
fi
echo "append root=/dev/${1}2 rw" >> sda1/syslinux.cfg
umount /dev/${1}1
umount /dev/${1}2
rmdir sda1
rmdir sda2
