#!/bin/sh
if [ $# -eq 0 ]
  then
    echo "Diska aukeratu behar duzu"
    lsblk | grep disk
    exit
fi
for n in /dev/$1* ; do umount $n ; done
swapoff --all
dd if=/dev/zero of=/dev/$1 bs=10240 count=1
parted -s /dev/$1 mklabel gpt  \
 mkpart primary fat32 0% 200MB  \
# mkpart ESP fat32 0% 200MB  \
 mkpart primary ext4 200MB 10GB  \
 mkpart primary ext4 10GB 20GB  \
 mkpart primary linux-swap 20GB 24GB  \
 mkpart primary ext4 24GB 100%  \
 set 1 legacy_boot on
# set 1 boot on
mkfs.vfat /dev/${1}1 -F 32 -n BOOT
mkfs.ext4 /dev/${1}2 -FL sistemaA
mkfs.ext4 /dev/${1}3 -FL sistemaB
mkswap /dev/${1}4
mkfs.ext4 /dev/${1}5 -FL home
dd bs=440 count=1 conv=notrunc if=/usr/lib/syslinux/mbr/gptmbr.bin of=/dev/$1
syslinux --install /dev/${1}1
mkdir sda1
mount /dev/${1}1 sda1
#mkdir -p sda1/EFI/boot
#cp syslinux_local.cfg sda1/EFI/boot/syslinux.cfg
#cp /usr/lib/SYSLINUX.EFI/efi64/syslinux.efi sda1/EFI/boot/bootx64.efi
#cp /usr/lib/syslinux/modules/efi64/libutil.c32 sda1/EFI/boot/
#cp /usr/lib/syslinux/modules/efi64/menu.c32 sda1/EFI/boot/
#cp /usr/lib/syslinux/modules/efi64/ldlinux.e64 sda1/EFI/boot/
cp syslinux_local.cfg sda1/syslinux.cfg
cp /boot/ipxe.lkrn sda1/
cp /usr/lib/syslinux/modules/bios/libutil.c32 sda1/
cp /usr/lib/syslinux/modules/bios/menu.c32 sda1/
cp /usr/lib/syslinux/modules/bios/ldlinux.c32 sda1/
mkdir sda2
mount /dev/${1}2 sda2
echo "irudia kopiatzen..."
pv /lib/live/mount/medium/live/filesystem.squashfs > sda2/filesystem.squashfs
cd sda2
echo "diskoan instalatzen..."
unsquashfs filesystem.squashfs
cd ..
mv sda2/squashfs-root/* sda2/
rmdir sda2/squashfs-root
rm sda2/filesystem.squashfs
echo "fstab eguneratzen..."
#echo "/dev/${1}1        /boot/efi           vfat    defaults                0 0" > sda2/etc/fstab
echo "/dev/${1}1        /boot           vfat    defaults                0 0" > sda2/etc/fstab
echo "/dev/${1}2    /                   ext4    defaults                0 0" >> sda2/etc/fstab
echo "/dev/${1}4    swap        swap    defaults                0 0" >> sda2/etc/fstab
echo "/dev/${1}5    /home       ext4    defaults                0 0" >> sda2/etc/fstab
echo "/dev/${1}3        /mnt/Hidden1    ext4    noauto,umask=222        0 0" >> sda2/etc/fstab
cp sda2/initrd.img sda1/
cp sda2/vmlinuz sda1/
echo "append root=/dev/${1}2 rw" >> sda1/syslinux.cfg
#echo "append root=/dev/${1}2 rw" >> sda1/EFI/boot/syslinux.cfg
umount /dev/${1}1
umount /dev/${1}2
rmdir sda1
rmdir sda2

