---
- name: Retroarch instalatu
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - qjoypad
    - retroarch
    - libqt5concurrent5

- name: Build-depends
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - debhelper
    - libasound2-dev
    - libavcodec-dev
    - libavdevice-dev
    - libavformat-dev
    - libavutil-dev
    - libc6-dev
    - libdrm-dev
    - libegl1-mesa-dev
    - libfreetype6-dev
    - libgbm-dev
    - libglm-dev
    - libjack-jackd2-dev
    - libminiupnpc-dev
    - libopenal-dev
    - libpulse-dev
    - libsdl2-dev
    - libswscale-dev
    - libudev-dev
    - libusb-1.0-0-dev
    - libv4l-dev
    - libvulkan-dev
    - libxinerama-dev
    - libxml2-dev
    - libxv-dev
    - libxxf86vm-dev
    - pkg-config
    - python3-dev
    - qtbase5-dev
    - x11proto-xext-dev
    - zlib1g-dev
    - libx11-xcb-dev

- name: jaitsi git
  git:
    repo: 'https://github.com/libretro/RetroArch'
    dest: /root/retroarch

#apt-cache showsrc retroarch | grep Build-Depends
- name: Configure
  command: "./configure"
  args:
    chdir: "/root/retroarch"

- name: Build
  make:
    chdir: /root/retroarch
#    params:
#      NUM_THREADS: 4

- name: Build install
  make:
    chdir: /root/retroarch
    target: install

- name: Remove retroarch build dependencies
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - debhelper
    - libasound2-dev
    - libavcodec-dev
    - libavdevice-dev
    - libavformat-dev
    - libavutil-dev
    - libc6-dev
    - libdrm-dev
    - libegl1-mesa-dev
    - libfreetype6-dev
    - libgbm-dev
    - libglm-dev
    - libjack-jackd2-dev
    - libminiupnpc-dev
    - libopenal-dev
    - libpulse-dev
    - libsdl2-dev
    - libswscale-dev
    - libudev-dev
    - libusb-1.0-0-dev
    - libv4l-dev
    - libvulkan-dev
    - libxinerama-dev
    - libxml2-dev
    - libxv-dev
    - libxxf86vm-dev
    - pkg-config
    - python3-dev
    - qtbase5-dev
    - x11proto-xext-dev
    - zlib1g-dev
    - libx11-xcb-dev

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

