---
- name: Copy modeline generator.
  copy:
    src: "{{ role_path }}/files/usr/local/bin/modelines"
    dest: "/user/local/bin/modelines"
    mode: 0755

- name: Copy modeline generator desktop to autostart.
  copy:
    src: "{{ role_path }}/files/usr/share/applications/modelines.desktop"
    dest: "/etc/xdg/autostart/modelines.desktop"
    mode: 0644

- name: Copy unmute desktop to autostart.
  copy:
    src: "{{ role_path }}/files/usr/share/applications/unmute.desktop"
    dest: "/etc/xdg/autostart/unmute.desktop"
    mode: 0644
