#this task installs and configures some programs for laptops
---
  - name: Install laptop task with tasksel
    command: /usr/bin/tasksel install laptop

  - name: Install tlp and pm-utils for battery use. Add some wireless chip firmwares.
    apt:
      name: "{{ packages }}"
    vars:
      packages:
       - network-manager
       - tlp
       - firmware-iwlwifi
       - firmware-atheros
       - pm-utils

#  - name: Create xfce config folder.
#    file:
#      path: "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml"
#      state: directory

  - name: Configure xfce so blocknum isn't enabled at startup.
    copy:
      src: "{{ role_path }}/files/keyboards.xml"
      dest: "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/keyboards.xml"
      mode: 0644

  - name: Show power manager trayicon.
    copy:
      src: "{{ role_path }}/files/xfce4-power-manager.xml"
      dest: "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml"
      mode: 0644

  - name: Power off wen lid is closed.
    replace:
      dest: /etc/systemd/logind.conf
      regexp: '#HandleLidSwitch=suspend'
      replace: 'HandleLidSwitch=poweroff'

#  - name: Lightdm autologin
#    replace:
#      dest: /etc/lightdm/lightdm.conf
#      regexp: '#autologin-user=usuario'
#      replace: 'autologin-user=usuario'

  - name: Configure our wifi network
    template:
      src: "{{ role_path }}/templates/Nagusia.j2"
      dest: /etc/NetworkManager/system-connections/Nagusia.nmconnection
      owner: root
      mode: '0600'
