#this task configures the desktop environmet for basque locale
---
- name: Install spanish and basque locale packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - aspell-eu
    - aspell-es
    - ispanish
    - wspanish
    - debian-reference-es
    - util-linux-locales
    - myspell-es
    - manpages-es

- name: Install spanish and basque locale for QT applications in Ubuntu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - manpages-es-extra
    - language-pack-kde-es
    - language-pack-kde-eu
    - language-pack-gnome-es
    - language-pack-gnome-eu
  when: ansible_distribution == 'Ubuntu'
