#this task configures xfce desktop for ubuntu or debian
---
- name: Config panel
  copy:
    src: "{{ role_path }}/files/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml"
    dest: "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml"
    mode: 0644

- name: Config panel 2
  copy:
    src: "{{ role_path }}/files/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml"
    dest: "/etc/xdg/xfce4/panel/default.xml"
    mode: 0644

- name: Config Whiskermenu
  copy:
    src: "{{ role_path }}/files/etc/xdg/xfce4/panel/whiskermenu-1.rc"
    dest: "/etc/xdg/xfce4/panel/whiskermenu-1.rc"
    mode: 0644

- name: Config keyboard shortcuts
  copy:
    src: "{{ role_path }}/files/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml"
    dest: "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml"
    mode: 0644

- name: Set bloqnum on by default
  copy:
    src: "{{ role_path }}/files/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/keyboards.xml"
    dest: "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/keyboards.xml"
    mode: 0644

- name: Config xfwm
  copy:
    src: "{{ role_path }}/files/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml"
    dest: "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml"
    mode: 0644

- name: Config power management
  copy:
    src: "{{ role_path }}/files/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml"
    dest: "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml"
    mode: 0644

- name: Config thunar
  copy:
    src: "{{ role_path }}/files/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/thunar.xml"
    dest: "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/thunar.xml"
    mode: 0644

- name: Config thunar
  copy:
    src: "{{ role_path }}/files/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml"
    dest: "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml"
    mode: 0644
