#this task installs chromium in Debian. It also sets some policies and installs two addons. 
---
- name: Install chromium
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - chromium
    - chromium-l10n

#This is for me. I don't want to use two different panel config files for chromium and chrome, so I rename it.
- name: Move desktop file to chrome.desktop
  command: mv /usr/share/applications/chromium.desktop /usr/share/applications/chrome.desktop

- name: Create chrome link in /usr/bin
  file:
    src: /usr/bin/chromium
    dest: /usr/bin/chrome
    state: link

- name: Set chromium master preferences
  copy:
    src: "{{ role_path }}/files/etc/chromium/master_preferences"
    dest: "/etc/chromium/master_preferences"
    mode: 0644

- name: Change default flags
  blockinfile:
    dest: "/etc/chromium.d/default-flags"
    block: |
      # Change password store to basic, so it doesn't complain at start
      export CHROMIUM_FLAGS="$CHROMIUM_FLAGS --password-store=basic"

- name: Create policies directory
  file:
    path: /etc/chromium/policies/managed
    state: directory
    mode: 0755

- name: Set chromium policies
  copy:
    src: "{{ role_path }}/files/etc/chromium/policies/managed/policies.json.mine"
    dest: "/etc/chromium/policies/managed/policies.json"
    mode: 0644

- name: Set firefox as default browser
  alternatives:
    name: x-www-browser
    path: /usr/bin/firefox

- name: Set firefox as default gnome-browser
  alternatives:
    name: gnome-www-browser
    path: /usr/bin/firefox
