#this task installs chromium in Debian. It also sets some policies and installs two addons. 
---
- name: Install chromium
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - chromium
    - chromium-l10n

#This is for me. I don't want to use two different panel config files for chromium and chrome, so I rename it.
- name: Check if original file exists.
  stat:
    path: "/usr/share/applications/chromium.desktop"
  register: desktop

- name: Move desktop file to chrome.desktop
  command: mv /usr/share/applications/chromium.desktop /usr/share/applications/chrome.desktop
  when: desktop.stat.exists == True 
  
- name: Create chrome link in /usr/bin
  file:
    src: /usr/bin/chromium
    dest: /usr/bin/chrome
    state: link

- name: Change default flags
  blockinfile:
    dest: "/etc/chromium.d/default-flags"
    block: |
      # Change password store to basic, so it doesn't complain at start
      export CHROMIUM_FLAGS="$CHROMIUM_FLAGS --password-store=basic"

- name: Create policies directory
  file:
    path: /etc/chromium/policies/managed
    state: directory
    mode: 0755

- name: Set chromium policies
  copy:
    src: "{{ role_path }}/files/etc/chromium/policies/managed/policies.json"
    dest: "/etc/chromium/policies/managed/policies.json"
    mode: 0644

- name: Set firefox as default browser
  alternatives:
    name: "{{ item }}"
    path: /usr/bin/firefox
  with_items:
    - x-www-browser
    - gnome-www-browser
