#This task installs some extra applications and configures them. 
---
- name: Install multimedia applications.
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - jclic
    - audacity
    - gthumb
    - skanlite
    - kolourpaint4
    - sound-juicer
    - cheese
    - vlc
    - winff
    - aegisub
    - aegisub-l10n
    - texlive-extra-utils
    - pdftk
    - cups-pdf
    - inkscape
    - gimp
    - xournal
    - openshot

- name: Change gthumb desktop file, to avoid dark theme.
  lineinfile:
    dest: "/usr/share/applications/org.gnome.gThumb.desktop"
    regexp: 'Exec=gthumb %U'
    line: 'Exec=env GTK_THEME=Adwaita gthumb %U'

- name: Install some programs for remote working.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - rdesktop
    - network-manager-openvpn-gnome

- name: Set default programs for different filetypes.
  copy:
    src: "{{ role_path }}/files/etc/xdg/mimeapps.list"
    dest: "/etc/xdg/mimeapps.list"
    mode: 0644
