#This task installs zoom program. 
---
- name: Create zoom folder.
  file:
    path: /root/zoom
    state: directory

- name: Download zoom i386.
  get_url:
    url: "https://zoom.us/client/latest/zoom_i386.deb"
    dest: "/root/zoom/zoom.deb"
    mode: 0644
  when: ansible_architecture == 'i386'

- name: Download zoom amd64.
  get_url:
    url: "https://zoom.us/client/latest/zoom_amd64.deb"
    dest: "/root/zoom/zoom.deb"
    mode: 0644
  when: ansible_architecture == 'x86_64'

- name: Extract zoom installer.
  command: dpkg-deb -R /root/zoom/zoom.deb /root/zoom/zoom
  args:
    warn: no

- name: Chage zoom dependencies, so it doesn't install ibus.
  replace:
    dest: /root/zoom/zoom/DEBIAN/control
    regexp: ', ibus'
    replace: ' '

- name: Create new zoom package.
  command: dpkg-deb -b /root/zoom/zoom /root/zoom/zoom2.deb
  args:
    warn: no

- name: Install zoom.
  apt:
    deb: "/root/zoom/zoom2.deb"

- name: Clean zoom files.
  file:
    path: "/root/zoom"
    state: absent
