#this role installs minimal xfce desktop with basque locale for debian or ubuntu
---

  - include: 00-minimal.yml

  - include: 01-lightdm.yml

  - include: 01-sddm.yml

  - include: 02-locales.yml

  - include: 03-xfce.yml

  - include: 04-firefox.yml

# I prefer to install google chrome in ubuntu, because chromium is a snap package. I use policies to control google's shit.
  - include: 05-chrome.yml
    when: ansible_distribution == 'Ubuntu'

  - include: 05-chromium.yml
    when: ansible_distribution == 'Debian'

  - include: 06-libreoffice.yml
