#this task configures the system to use basque locale
---
- name: Install basque and spanish locales in ubuntu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - language-pack-es
    - language-pack-eu
  when: ansible_distribution == 'Ubuntu'

- name: Add spanish locale
  locale_gen:
    name: es_ES.UTF-8
    state: present

- name: Add basque locale
  locale_gen:
    name: eu_ES.UTF-8
    state: present

- name: Dpkg-reconfigure locales.
  command: /usr/sbin/dpkg-reconfigure --frontend=noninteractive locales

- name: Update-locale. Locale is set to basque, with spanish as fallback.
  command: /usr/sbin/update-locale LANG=eu_ES.UTF-8 LANGUAGE=eu:es
