---
- name: Add updates repository 
  apt_repository:
    repo: deb {{ repo }} {{ ansible_distribution_release }}-updates {{ compo }}
    state: present

- name: Add backports repository 
  apt_repository:
    repo: deb {{ repo }} {{ ansible_distribution_release }}-backports {{ compo }}
    state: present

- name: Add Debian security repository
  apt_repository:
    repo: deb http://security.debian.org/debian-security {{ ansible_distribution_release }}/updates {{ compo }}
    state: present
  when: ansible_distribution == 'Debian'

- name: Add Ubuntu security repository
  apt_repository:
    repo: deb http://security.ubuntu.com/ubuntu {{ ansible_distribution_release }}-security {{ compo }}
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
