#this task installs the kernel for debian or ubuntu
---
- name: Install i386 kernel for Debian.
  apt: name=linux-image-686-pae
  when:
    - ansible_distribution == 'Debian'
    - ansible_architecture == 'i386'

- name: Install amd64 kernel for Debian.
  apt: name=linux-image-amd64
  when:
    - ansible_distribution == 'Debian'
    - ansible_architecture == 'x86_64'

- name: Install amd64 kernel for Ubuntu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - linux-image-generic
  when: ansible_distribution == 'Ubuntu'
