#this task installs the kernel for debian or ubuntu and disables pcspeaker
---
- name: Disable pcspeaker.
  lineinfile:
    create: yes
    path: "/etc/modprobe.d/nobeep.conf"
    line: "blacklist pcspkr"
#now run 'depmod -a'?

- name: Quiet pcspeaker.
  replace:
    dest: "/etc/inputrc"
    regexp: "# set bell-style none"
    replace: "set bell-style none"
# set bell-style visible?

- name: Install i386 kernel for Debian.
  apt: name=linux-image-686-pae
  when:
    - ansible_distribution == 'Debian'
    - ansible_architecture == 'i386'

- name: Install amd64 kernel for Debian.
  apt: name=linux-image-amd64
  when:
    - ansible_distribution == 'Debian'
    - ansible_architecture == 'x86_64'

- name: Install amd64 kernel for Ubuntu. We're installing lilo to avoid grub installation.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - linux-image-generic
    - lilo
  when: ansible_distribution == 'Ubuntu'
