#Install tasksel and standard packages
---
- name: Install tasksel.
  apt:
    name: tasksel
    install_recommends: no

- name: Install standard tasksel packages.
  command: /usr/bin/tasksel --new-install install standard

#add PPA and autoupdate
- name: Install software-properties-common.
  apt:
    name: software-properties-common
    install_recommends: no
