#this task adds some basic packages to ur live system
---
- name: Update everything to the latest version.
  apt:
    upgrade: dist

- name: Install my custom pacakges.
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - rsync
    - screen
    - nfs-common
    - watchdog
    - wget
    - atool
    - zip
    - unzip
    - rar
    - p7zip-full
    - dosfstools
    - ipxe
    - network-manager
    - sudo
    - inxi
    - ntfs-3g
    - cifs-utils

- name: Install some non-free firwmares.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - firmware-linux
    - firmware-linux-nonfree

#- name: Install grub.
#  apt:
#    name: "{{ packages }}"
#  vars:
#    packages:
#    - grub-pc

#- name: Istall grub EFI
#  apt:
#    name: "{{ packages }}"
#  vars:
#    packages:
#    - grub-efi-amd64-signed
#  when: ansible_architecture == 'x86_64'
