#this task adds some basic packages to ur live system
---
- name: Update everything to the latest version.
  apt:
    upgrade: dist

- name: Install my custom pacakges.
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - rsync
    - screen
    - nfs-common
    - watchdog
    - wget
    - atool
    - zip
    - unzip
    - rar
    - p7zip-full
    - dosfstools
    - ipxe
    - network-manager
    - sudo
    - inxi
    - ntfs-3g
    - cifs-utils

- name: Install some non-free firwmares. Debian.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - firmware-linux
    - firmware-linux-nonfree
  when: ansible_distribution == 'Debian'

- name: Install some non-free firwmares. Ubuntu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - linux-firmware
  when: ansible_distribution == 'Ubuntu'

- name: Install grub.
  apt:
    name: grub-pc

- name: Istall grub EFI
  apt:
    name: grub-efi-amd64-signed
  when: ansible_architecture == 'x86_64'
