#some custom tweaks
---
- name: Copy custom scripts
  copy:
    src: "{{ role_path }}/files/usr/local/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
  with_items:
     - mute
     - unmute
     - wifion
     - disableswap

- name: Power button will power off the system.
  replace:
    dest: /etc/systemd/logind.conf
    regexp: '#HandlePowerKey=poweroff'
    replace: 'HandlePowerKey=poweroff'

- name: Set custom grub options.
  replace:
    dest: /etc/default/grub
    regexp: "{{ item.old }}"
    replace: "{{ item.new }}"
#    backrefs: yes
  with_items:
     - { old: 'GRUB_TIMEOUT=5', new: 'GRUB_TIMEOUT=2' }
     - { old: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet"', new: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet"' }
     - { old: 'GRUB_DISABLE_OS_PROBER="false"', new: 'GRUB_DISABLE_OS_PROBER="true"' }

#https://askubuntu.com/questions/907246/how-to-disable-systemd-resolved-in-ubuntu/1195074#1195074
#- name: Remove resolv.conf.
#  file:
#    path: /etc/resolv.conf
#    state: absent

#- name: Disable systemd-resolved.
#  lineinfile:
#    dest: /etc/systemd/resolved.conf
#    regexp: '#DNSStubListener=yes'
#    line: 'DNSStubListener=no'
#    backrefs: yes

#- name: Let Network-manager configure DNS.
#  lineinfile:
#    dest: /usr/lib/NetworkManager/conf.d/10-dns-resolved.conf
#    regexp: 'dns=systemd-resolved'
#    line: '#dns=systemd-resolved'
#    backrefs: yes
#  when: ansible_distribution == 'Ubuntu'
