#this task adds some basic packages to ur live system
---
- name: Update everything to the latest version.
  apt:
    upgrade: dist

- name: Install my custom pacakges.
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - rsync
    - screen
    - nfs-common
    - watchdog
    - wget
    - atool
    - zip
    - unzip
    - bzip2
    - rar
    - p7zip-full
    - dosfstools
    - ipxe
    - network-manager
    - sudo
    - inxi
    - ntfs-3g
    - cifs-utils
