#some custom scripts to install the live system in local hard disk
---
- name: Copy installers
  copy:
    src: "{{ role_path }}/files/usr/local/sbin/{{ item }}"
    dest: "/usr/local/sbin/{{ item }}"
    mode: 0755
  with_items:
     - formatallbios
     - formatalluefi

- name: Copy custom scripts
  copy:
    src: "{{ role_path }}/files/usr/local/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
  with_items:
     - gethardinfo
     - getnamebymac
     - mute
     - unmute
     - wifion
     - disableswap

- name: Copy basic syslinux_local.cfg
  copy:
    src: "{{ role_path }}/files/root/syslinux_local.cfg"
    dest: "/root/syslinux_local.cfg"
    mode: 0644
