---
#passwords are created with 'mkpasswd --method=sha-512'. you must install whois package to use it.
    - name: Create a new user in Debian.
      user:
         name: usuario
         password: $6$vBArPwq8I$Th2XJs3z57iisxQCEgHmsrIAFuTyMPzJ7BsDt5uqPpfg3fAGSuYLl/ij6u2tfsbigUxllkAF.FvpCscdKbV8F1
         shell: /bin/bash
         createhome: no
         groups: cdrom,floppy,audio,dip,video,plugdev,netdev,sudo
      when: ansible_distribution == 'Debian'

    - name: Create a new user in Ubuntu.
      user:
         name: usuario
         password: $6$vBArPwq8I$Th2XJs3z57iisxQCEgHmsrIAFuTyMPzJ7BsDt5uqPpfg3fAGSuYLl/ij6u2tfsbigUxllkAF.FvpCscdKbV8F1
         shell: /bin/bash
         createhome: no
         groups: adm,cdrom,dip,plugdev,sudo
      when: ansible_distribution == 'Ubuntu'

    - name: User home will be created at first login.
      replace:
        dest: /usr/share/pam-configs/mkhomedir
        regexp: 'Default: no'
        replace: 'Default: yes'

    - name: pam-auth-update
      command: pam-auth-update --package --enable mkhomedir
      args:
        warn: no
