#configure the system to be live
---
- name: Install live-boot packages and haveged.
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - live-boot
    - haveged

#Don't disconnect the net before shutting down. This is a pxe live system, so disconnecting would interrupt the shutdown process.
- name: Create a folder for ifup@.service and networking.service
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/etc/systemd/system/ifup@.service.d/"
    - "/etc/systemd/system/networking.service.d/"
  when: ansible_distribution == 'Debian'

- name: Override default networking and ifup configuration. Now Debian won't disconnect before shutting down.
  copy:
    src: "{{ role_path }}/files/etc/systemd/system/networking.service.d/override.conf"
    dest: "{{ item }}"
    mode: 0644
  with_items:
    - "/etc/systemd/system/networking.service.d/override.conf"
    - "/etc/systemd/system/ifup@.service.d/override.conf"
  when: ansible_distribution == 'Debian'

#DNS aren't configured in our ubuntu live system, I don't know why. Disabling systemd-resolved fixes the problem.
- name: Disable systemd-resolved service.
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/systemd/system/sysinit.target.wants/systemd-resolved.service"
    - "/etc/systemd/system/dbus-org.freedesktop.resolve1.service"
    - "/etc/resolv.conf"
  when: ansible_distribution == 'Ubuntu'

- name: Disable systemd-resolved in network-manager.
  lineinfile:
    dest: /usr/lib/NetworkManager/conf.d/10-dns-resolved.conf
    regexp: 'dns=systemd-resolved'
    line: '#dns=systemd-resolved'
    backrefs: yes
  when: ansible_distribution == 'Ubuntu'

- name: Dont save systemd journal. This is a live system we dont need it.
  replace:
    dest: /etc/systemd/journald.conf
    regexp: '#Storage=auto'
    replace: 'Storage=none'

#our systems name will be its mac address
- name: Copy getnamebymac script
  copy:
    src: "{{ role_path }}/files/usr/local/bin/getnamebymac"
    dest: "/usr/local/bin/getnamebymac"
    mode: 0755

- name: Copy getnamebymac service.
  copy:
    src: "{{ role_path }}/files/etc/systemd/system/getnamebymac.service"
    dest: "/etc/systemd/system/getnamebymac.service"
    mode: 0644

- name: Enable getnamebymac service.
  file:
    src: "/etc/systemd/system/getnamebymac.service"
    dest: "/etc/systemd/system/multi-user.target.wants/getnamebymac.service"
    state: link

- name: Don't auto update apt
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/systemd/system/timers.target.wants/apt-daily.timer"
    - "/etc/systemd/system/timers.target.wants/apt-daily-upgrade.timer"

#those two tasks prepare the live system to be installable to the hard disk
- name: Install needed programs.
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - pv
    - squashfs-tools
    - parted

- name: Copy installers
  copy:
    src: "{{ role_path }}/files/usr/local/sbin/{{ item }}"
    dest: "/usr/local/sbin/{{ item }}"
    mode: 0755
  with_items:
     - format_newinstall
     - format_update
