#this task will configure basque locale, keyboard and timezonne. will add some repositories and install basic packages
#it will add some config tweaks, custom scripts and add a user with sudo privileges
---
  - include_vars: "{{ distro }}.yml"

  - include: 01-locale.yml

  - include: 02-keyboard.yml

  - include: 03-timezone.yml

  - include: 04-repositories.yml

  - include: 05-kernel.yml

  - include: 06-tasksel.yml

  - include: 07-packages.yml

  - include: 08-live.yml

  - include: 09-customscripts.yml

  - include: 10-users.yml
