#this role will clean temporary files from a debootstraped system and compress it in a squashfs file
---
  - name: delete hostname, the client will get one at boot
    shell: /bin/rm -rf {{ inventory_hostname }}/live/squashfs-root/etc/hostname
    args:
      warn: no

  - name: cleanup | sparse files
    shell: /bin/rm -rf {{ inventory_hostname }}/live/squashfs-root/var/cache/apt/archives/*.deb
    args:
      warn: no

  - name: cleanup | sparse files
    shell: /bin/rm -rf {{ inventory_hostname }}/live/squashfs-root/var/cache/apt/archives/partial/*
    args:
      warn: no

  - name: cleanup | sparse files
    shell: /bin/rm -rf {{ inventory_hostname }}/live/squashfs-root/var/cache/debconf/*-old
    args:
      warn: no

  - name: cleanup | sparse files
    shell: /bin/rm -rf {{ inventory_hostname }}/live/squashfs-root/var/lib/apt/lists/*
    args:
      warn: no

  - name: Copy vmlinuz Debian
    copy:
      src: "{{ inventory_hostname }}/live/squashfs-root/vmlinuz"
      dest: "{{ inventory_hostname }}/vmlinuz"
      mode: 0644
    when: distro == 'debian'

  - name: Copy initrd Debian
    copy:
      src: "{{ inventory_hostname }}/live/squashfs-root/initrd.img"
      dest: "{{ inventory_hostname }}/initrd.img"
      mode: 0644
    when: distro == 'debian'

  - name: Copy vmlinuz Ubuntu
    copy:
      src: "{{ inventory_hostname }}/live/squashfs-root/boot/vmlinuz"
      dest: "{{ inventory_hostname }}/vmlinuz"
      mode: 0644
    when: distro == 'ubuntu'

  - name: Copy initrd Ubuntu
    copy:
      src: "{{ inventory_hostname }}/live/squashfs-root/boot/initrd.img"
      dest: "{{ inventory_hostname }}/initrd.img"
      mode: 0644
    when: distro == 'ubuntu'

  - name: Create filesystem.squashfs file
    command: chdir={{ inventory_hostname }}/live mksquashfs squashfs-root filesystem.squashfs

  - name: Remove squashfs-root folder
    file: 
      path="{{ inventory_hostname }}/live/squashfs-root"
      state=absent
