#install and configure pxelinux for bios and uefi based clients
---
- name: Install pxelinux packages.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - pxelinux
    - syslinux-efi

- name: Create syslinux directories.
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
     - "{{ tftp_root }}/syslinux/bios/pxelinux.cfg"
     - "{{ tftp_root }}/syslinux/efi"

- name: Link both config files so we only need to update one.
  file:
    src: "{{ tftp_root }}/syslinux/bios/pxelinux.cfg"
    dest: "{{ tftp_root }}/syslinux/efi/pxelinux.cfg"
    state: link

- name: Create a link to the tftp-root inside syslinux folder.
  file:
    src: "{{ tftp_root }}"
    dest: "{{ tftp_root }}/syslinux/{{ item }}/tftp"
    state: link
  with_items:
     - bios
     - efi

- name: Copy needed syslinux files. Bios.
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  with_items:
     - { src: "/usr/lib/PXELINUX/pxelinux.0", dest: "{{ tftp_root }}/syslinux/bios/syslinux.0" }
     - { src: "/usr/lib/syslinux/modules/bios/libutil.c32", dest: "{{ tftp_root }}/syslinux/bios/libutil.c32" }
     - { src: "/usr/lib/syslinux/modules/bios/ldlinux.c32", dest: "{{ tftp_root }}/syslinux/bios/ldlinux.c32" }
     - { src: "/usr/lib/syslinux/modules/bios/menu.c32", dest: "{{ tftp_root }}/syslinux/bios/menu.c32" }
     - { src: "/usr/lib/syslinux/modules/bios/libcom32.c32", dest: "{{ tftp_root }}/syslinux/bios/libcom32.c32" }
     - { src: "/usr/lib/syslinux/modules/bios/syslinux.c32", dest: "{{ tftp_root }}/syslinux/bios/syslinux.c32" }
     - { src: "/usr/lib/syslinux/modules/bios/chain.c32", dest: "{{ tftp_root }}/syslinux/bios/chain.c32" }
     - { src: "/usr/lib/syslinux/modules/bios/linux.c32", dest: "{{ tftp_root }}/syslinux/bios/linux.c32" }

- name: Copy needed syslinux files. Uefi.
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  with_items:
     - { src: "/usr/lib/SYSLINUX.EFI/efi64/syslinux.efi", dest: "{{ tftp_root }}/syslinux/efi/syslinux.efi" }
     - { src: "/usr/lib/syslinux/modules/efi64/libutil.c32", dest: "{{ tftp_root }}/syslinux/efi/libutil.c32" }
     - { src: "/usr/lib/syslinux/modules/efi64/ldlinux.e64", dest: "{{ tftp_root }}/syslinux/efi/ldlinux.e64" }
     - { src: "/usr/lib/syslinux/modules/efi64/menu.c32", dest: "{{ tftp_root }}/syslinux/efi/menu.c32" }
     - { src: "/usr/lib/syslinux/modules/efi64/libcom32.c32", dest: "{{ tftp_root }}/syslinux/efi/libcom32.c32" }
     - { src: "/usr/lib/syslinux/modules/efi64/syslinux.c32", dest: "{{ tftp_root }}/syslinux/efi/syslinux.c32" }
     - { src: "/usr/lib/syslinux/modules/efi64/chain.c32", dest: "{{ tftp_root }}/syslinux/efi/chain.c32" }
     - { src: "/usr/lib/syslinux/modules/efi64/linux.c32", dest: "{{ tftp_root }}/syslinux/efi/linux.c32" }

- name: Copy pxelinux default config file
  template:
    src: "{{ role_path }}/templates/tftproot/syslinux/pxelinux.j2"
    dest: "{{ tftp_root }}/syslinux/bios/pxelinux.cfg/default"
    mode: 0644
