#install and configure grub for bios and uefi based clients
---
- name: Install grub packages.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - grub-efi-amd64-signed
    - grub-pc

- name: Create grub config folder.
  file:
    path: "{{ tftp_root }}/grub"
    state: directory
    mode: 0755

- name: Create a link to the tftp-root inside grub's folder.
  file:
    src: "{{ tftp_root }}"
    dest: "{{ tftp_root }}/grub/tftp"
    state: link

- name: Fill grub config diectory.
  command: /usr/bin/grub-mknetdir --net-directory={{ tftp_root }} --subdir=/grub

- name: Copy default grub.cfg.
  template:
    src: "{{ role_path }}/templates/tftproot/grub/grub.j2"
    dest: "{{ tftp_root }}/grub/grub.cfg"
    mode: 0644

- name: Create grub image for bios based clients.
  command: /usr/bin/grub-mkimage -d /usr/lib/grub/i386-pc/ -O i386-pc-pxe -o {{ tftp_root }}/grub/booti386.0 -p '(tftp,{{ ansible_default_ipv4.address }})/grub' pxe tftp

- name: Create grub image for uefi based clients.
  command: /usr/bin/grub-mkimage -d /usr/lib/grub/x86_64-efi/ -O x86_64-efi -o {{ tftp_root }}/grub/bootx64.efi -p '(tftp,{{ ansible_default_ipv4.address }})/grub' efinet tftp
