#prepare the server to create custom livecds
---
- name: Install needed pacakges.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - debootstrap
    - squashfs-tools
    - whois
    - zstd
#whois package will be used to create user passwords
#zstd is required in jammy for apt

- name: Create customubuntu dir.
  file:
    path: "{{ tftp_root }}/livecds/customubuntu"
    state: directory
    mode: 0755

- name: Create customdebian dir.
  file:
    path: "{{ tftp_root }}/livecds/customdebian"
    state: directory
    mode: 0755
    
#- name: Install newer version of debootstrap
#  apt:
#    deb: "http://es.archive.ubuntu.com/ubuntu/pool/main/d/debootstrap/debootstrap_1.0.126+nmu1_all.deb"
