#this role will configure a pxe/nfs server with syslinux, grub and ipxe. then it will add debian installer livecds launcher and windows installer
#livecds must be created with another role and windows installer files must be added from official isos
---

  - include_tasks: 01-server.yml

  - include_tasks: 02-syslinux.yml

  - include_tasks: 03-grub.yml

  - include_tasks: 04-ipxe.yml

  - include_tasks: 05-installers.yml
    when: ansible_distribution == 'Debian'

  - include_tasks: 06-livesystems.yml

  - include_tasks: 07-windows.yml
