#this role will configure a pxe/nfs server with syslinux, grub and ipxe. then it will add debian installer livecds launcher and windows installer
#livecds must be created with another role and windows installer files must be added from official isos
---

  - include: 01-server.yml

  - include: 02-syslinux.yml

  - include: 03-grub.yml

  - include: 04-ipxe.yml

  - include: 05-installers.yml

  - include: 06-livesystems.yml

  - include: 07-windows.yml
