---
- name: Install depends on i386
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - libasound2 
    - libbluetooth3 
    - libc6 
    - libcurl4 
    - libfontconfig1 
    - libfreetype6 
    - libgcc1 
    - libgl1-mesa-glx 
    - libglib2.0-0 
    - libgtk2.0-0 
    - libice6 
    - libnspr4 
    - libsm6 
    - libstdc++6 
    - libudev1 
    - libuuid1 
    - libx11-6 
    - libxext6 
    - libxinerama1 
    - libxkbfile1 
    - libxml2 
    - libxrender1 
    - libxtst6 
    - zlib1g 
    - libxslt1.1 
    - libltdl7
    - libusb-1.0-0
  when: ansible_architecture == 'i386'

- name: Add i386 packages
  command: /usr/bin/dpkg --add-architecture i386
  when: ansible_architecture == 'x86_64'

- name: apt-get update
  apt:
    update_cache: yes
  when: ansible_architecture == 'x86_64'

- name: Install depends on amd64
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - libasound2:i386
    - libbluetooth3:i386
    - libc6:i386
    - libcurl4:i386
    - libfontconfig1:i386
    - libfreetype6:i386
    - libgcc1:i386
    - libgl1-mesa-glx:i386
    - libglib2.0-0:i386
    - libgtk2.0-0:i386
    - libice6:i386
    - libnspr4:i386
    - libsm6:i386
    - libstdc++6:i386
    - libudev1:i386
    - libuuid1:i386
    - libx11-6:i386
    - libxext6:i386
    - libxinerama1:i386
    - libxkbfile1:i386
    - libxml2:i386
    - libxrender1:i386
    - libxtst6:i386
    - zlib1g:i386
    - libxslt1.1:i386 
    - libltdl7:i386
    - libusb-1.0-0:i386
  when: ansible_architecture == 'x86_64'

- name: link libudev1 and libudev0
  file:
    src: /lib/i386-linux-gnu/libudev.so.1
    dest: /lib/i386-linux-gnu/libudev.so.0
    state: link
