#this task creates a local user and configures sudo, so LDAP users can run the software without issues.
---
- name: Create local user "smart".
  user:
    name: smart
    shell: /bin/bash
    createhome: yes
    home: /erab/smart

- name: Let domain users run programs as "smart" user, without password.
  blockinfile:
    create: yes
    dest: "/etc/sudoers"
    marker: "#These users can run smart"
    block: |
      %lizarra\ ikastola ALL=(smart) NOPASSWD: ALL
      usuario ALL=(smart) NOPASSWD: ALL

- name: Copy smartsudo command.
  copy:
    src: "{{ role_path }}/files/usr/local/bin/smartsudo"
    dest: "/usr/local/bin/smartsudo"
    mode: 0755

- name: Remove official autostart service.
  file:
    path: /etc/xdg/autostart/smart_1-_Service.desktop
    state: absent

- name: Remove official autostart program.
  file:
    path: /etc/xdg/autostart/smart_1-_Tools.desktop 
    state: absent

- name: Copy my own smart launcher.
  copy:
    src: "{{ role_path }}/files/usr/share/applications/smartboard.desktop"
    dest: "/usr/share/applications/smartboard.desktop"
    mode: 0644

- name: Remove desktop files.
  file:
    path: "/usr/share/applications/{{ files }}"
    state: absent
  vars:
    files:
    - smartboard.desktop
    - smarttech-ControlPanel.desktop
    - smarttech-EssentialsForEducators.desktop
    - smarttech-gallery.desktop
    - smarttech-galleryitem.desktop
    - smarttech-GallerySetup.desktop
    - smarttech-LanguageSetup.desktop
    - smarttech-Magnifier.desktop
    - smarttech-notebook.desktop
    - smarttech-Orient.desktop
    - smarttech-Pointer.desktop
    - smarttech-ScreenCapture.desktop
    - smarttech-ScreenShade.desktop
    - smarttech-ScreenSpotlight.desktop
    - smarttech-SMARTBoardTools.desktop
    - smarttech-SMARTKeyboard.desktop

- name: Remove directory files.
  file:
    path: "/usr/share/desktop-directories/{{ files }}"
    state: absent
  vars:
    files:
    - smarttech-software.directory
    - smarttech-software-drivers.directory
    - smarttech-software-notebook.directory
    - smarttech-software-tools.directory
    - smarttech-software-update.directory
