#this task installs needed packages
---
- name: Install needed packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apache2
    - php
    - php-ldap
    - php-mbstring
    - php7.3-mbstring
