#this task installs and configures self-service password website. So users can change their password from browser.
---
  - include: 00-depends.yml

  - include: 01-download.yml

  - include: 02-apache.yml

  - include: 03-ssp.yml
