---
  - name: konfigurazioaren kopia egin
    copy:
      src: /var/www/html/self-service-password-master/conf/config.inc.php
      dest: /var/www/html/self-service-password-master/conf/config.inc.php.bak
      mode: 0644

  - name: gure konfigurazioa jarri
    template:
      src: "{{ role_path }}/templates/config.j2"
      dest: /var/www/html/self-service-password-master/conf/config.inc.php
      owner: root
      mode: '0644'


