---
- hosts: all
  connection: local
  roles:
    - debootstrap

- hosts: all
  connection: chroot
  vars:
    ansible_host: "{{ inventory_hostname }}/live/squashfs-root"
  tasks:
    - include: prepare.yml
    - include_role:
        name: minimal
    - include: exit.yml

- hosts: desktops
  connection: chroot
  vars:
    ansible_host: "{{ inventory_hostname }}/live/squashfs-root"
  tasks:
    - include: prepare.yml
    - include_role:
        name: desktop
    - include: exit.yml

- hosts: all
  connection: local
  roles:
    - squash
