#this will be executed before exiting the chroot
---
- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Umount /dev/pts
  command: umount -df /dev/pts
  args:
    warn: no

- name: Umount /sys
  command: umount -df /sys
  args:
    warn: no

- name: Umount /proc
  command: umount -df /proc
  args:
    warn: no
