#this will be executed inside the chroot to avoid errors
---
- name: Mount proc
  mount:
    src: none
    path: /proc
    fstype: proc
    state: mounted

- name: Mount sys
  mount:
    src: none
    path: /sys
    fstype: sysfs
    state: mounted

- name: Mount devpts
  mount:
    src: none
    path: /dev/pts
    fstype: devpts
    state: mounted

- name: inside chroot ansible gets server's architecture, so we fix it
  set_fact:
    ansible_architecture: i386
  when: arch == 'i386'

- name: Run the equivalent of "apt-get update"
  apt:
    update_cache: yes
