#Install tasksel and standard packages. If you want to know what's installed...
---
- name: Install tasksel.
  apt:
    name: tasksel
    install_recommends: no

#- name: Install standard tasksel packages.
#  command: /usr/bin/tasksel --new-install install standard
#  when: ansible_distribution == 'Debian'

#tasksel --new-install install standard --debconf-apt-progress "--logfile packages"
- name: Install standard tasksel packages. Ubuntu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - linux-image-generic
    - apparmor
    - bash-completion
    - bind9-dnsutils
    - bind9-host
    - bind9-libs
    - bsdextrautils
    - busybox-static
    - command-not-found
    - dosfstools
    - ed
    - file
    - friendly-recovery
    - ftp
    - fuse3
    - groff-base
    - hdparm
    - inetutils-telnet
    - info
    - install-info
    - iptables
    - iputils-tracepath
    - irqbalance
    - libcbor0.10
    - libdrm-common
    - libdrm2
    - libedit2
    - libfido2-1
    - libgdbm6
    - libgpm2
    - libip6tc2
    - libjansson4
    - liblmdb0
    - libmagic-mgc
    - libmagic1
    - libmaxminddb0
    - libncurses6
    - libnetfilter-conntrack3
    - libnfnetlink0
    - libnftables1
    - libnftnl11
    - libnghttp2-14
    - libntfs-3g89
    - libnuma1
    - libparted2
    - libpcap0.8
    - libpci3
    - libpipeline1
    - libplymouth5
    - libpsl5
    - libuchardet0
    - libunwind8
    - libuv1
    - libx11-6
    - libx11-data
    - libxau6
    - libxcb1
    - libxdmcp6
    - libxext6
    - libxmuu1
    - lshw
    - lsof
    - man-db
    - manpages
    - mtr-tiny
    - nano
    - nftables
    - ntfs-3g
    - openssh-client
    - parted
    - pci.ids
    - pciutils
    - plymouth
    - plymouth-theme-ubuntu-text
    - powermgmt-base
    - psmisc
    - publicsuffix
    - python3-commandnotfound
    - python3-distro-info
    - python3-distupgrade
    - python3-gdbm
    - python3-update-manager
    - strace
    - tcpdump
    - telnet
    - time
    - tnftp
    - ubuntu-release-upgrader-core
    - ubuntu-standard
    - ufw
    - update-manager-core
    - usb.ids
    - usbutils
    - wget
    - xauth
    - xz-utils
  when: ansible_distribution == 'Ubuntu'

- name: Install standard tasksel packages. Debian.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apt-listchanges
    - bash-completion
    - bind9-dnsutils
    - bind9-host
    - bind9-libs
    - bsdextrautils
    - bzip2
    - ca-certificates
    - dbus
    - dbus-bin
    - dbus-daemon
    - dbus-session-bus-common
    - dbus-system-bus-common
    - dbus-user-session
    - debian-faq
    - distro-info-data
    - doc-debian
    - file
    - gettext-base
    - groff-base
    - inetutils-telnet
    - iso-codes
    - krb5-locales
    - libbrotli1
    - libcbor0.8
    - libcurl3-gnutls
    - libdbus-1-3
    - libexpat1
    - libfido2-1
    - libfstrm0
    - libgdbm-compat4
    - libgdbm6
    - libicu72
    - libjemalloc2
    - libldap-2.5-0
    - libldap-common
    - liblmdb0
    - liblockfile-bin
    - libmagic-mgc
    - libmagic1
    - libmaxminddb0
    - libnghttp2-14
    - libnsl2
    - libnss-systemd
    - libpam-systemd
    - libpci3
    - libperl5.36
    - libpipeline1
    - libprotobuf-c1
    - libpsl5
    - libpython3-stdlib
    - libpython3.11-minimal
    - libpython3.11-stdlib
    - librtmp1
    - libsasl2-2
    - libsasl2-modules
    - libsasl2-modules-db
    - libsqlite3-0
    - libssh2-1
    - libuchardet0
    - libuv1
    - libx11-6
    - libx11-data
    - libxau6
    - libxcb1
    - libxdmcp6
    - libxext6
    - libxml2
    - libxmuu1
    - lsb-release
    - lsof
    - mailcap
    - man-db
    - manpages
    - media-types
    - mime-support
    - ncurses-term
    - netcat-traditional
    - openssh-client
    - pci.ids
    - pciutils
    - perl
    - perl-modules-5.36
    - publicsuffix
    - python-apt-common
    - python3
    - python3-apt
    - python3-certifi
    - python3-chardet
    - python3-charset-normalizer
    - python3-debconf
    - python3-debian
    - python3-debianbts
    - python3-httplib2
    - python3-idna
    - python3-minimal
    - python3-pkg-resources
    - python3-pycurl
    - python3-pyparsing
    - python3-pysimplesoap
    - python3-reportbug
    - python3-requests
    - python3-six
    - python3-urllib3
    - python3.11
    - python3.11-minimal
    - reportbug
    - systemd-timesyncd
    - traceroute
    - ucf
    - wamerican
    - wget
    - xauth
    - xz-utils
  when: ansible_distribution == 'Debian'

#add PPA and autoupdate
- name: Install software-properties-common.
  apt:
    name: software-properties-common
    install_recommends: no
