#some custom tweaks
---
- name: Disable pcspeaker.
  lineinfile:
    create: yes
    path: "/etc/modprobe.d/nobeep.conf"
    line: "blacklist pcspkr"
#now run 'depmod -a'?

- name: Quiet pcspeaker.
  replace:
    dest: "/etc/inputrc"
    regexp: "# set bell-style none"
    replace: "set bell-style none"
# set bell-style visible?

- name: Copy custom scripts
  copy:
    src: "{{ role_path }}/files/usr/local/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
  with_items:
     - mute
     - unmute
     - wifion

- name: Power button will power off the system.
  replace:
    dest: /etc/systemd/logind.conf
    regexp: '#HandlePowerKey=poweroff'
    replace: 'HandlePowerKey=poweroff'

- name: Set custom grub options
  lineinfile:
    dest: /etc/default/grub
    regexp: "{{ item.old }}"
    line: "{{ item.new }}"
  with_items:
     - { old: '^(.*)GRUB_TIMEOUT=(.*)$', new: 'GRUB_TIMEOUT=2' }
     - { old: '^(.*)GRUB_TIMEOUT_STYLE=(.*)$', new: 'GRUB_TIMEOUT_STYLE="menu"' }
     - { old: '^(.*)GRUB_CMDLINE_LINUX_DEFAULT=(.*)$', new: 'GRUB_CMDLINE_LINUX_DEFAULT=""' }
     - { old: '^(.*)GRUB_DISABLE_OS_PROBER=(.*)$', new: 'GRUB_DISABLE_OS_PROBER="true"' }

- name: Fix ubuntu's 30 second bug in grub.
  lineinfile:
    path: /etc/default/grub
    insertafter: 'GRUB_TIMEOUT=2'
    line: 'GRUB_RECORDFAIL_TIMEOUT=2'
  when: ansible_distribution == 'Ubuntu'

- name: Let NetworkManager manage all devices on this system. Ubuntu.
  copy:
    src: "{{ role_path }}/files/etc/netplan/01-network-manager-all.yaml"
    dest: "/etc/netplan/01-network-manager-all.yaml"
    mode: 0644
  when: ansible_distribution == 'Ubuntu'

#DNS aren't configured in our ubuntu live system, I don't know why. Disabling DNSStubListener fixes the problem.
- name: Disable DNSStubListener.
  replace:
    dest: "/etc/systemd/resolved.conf"
    regexp: "#DNSStubListener=yes"
    replace: "DNSStubListener=no"
  when: ansible_distribution == 'Ubuntu'
