---
- name: Remove build tools
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - build-essential
    - git

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
