---
- name: Create a new user in Debian.
  user:
     name: arcade
     password: $6$eK09oKpkO3J$hSDmoqY8WJX5pbMYNcQ7/p8LNR8p.18vhaoIYwc9uhcbOKuYPK10P6oCSNRTp/Cd8YiSwte9VB32GyVhkPLWV.
     shell: /bin/bash
     createhome: no
     groups: cdrom,floppy,audio,dip,video,plugdev,netdev,sudo
  when: ansible_distribution == 'Debian'

- name: Create a new user in Ubuntu.
  user:
     name: arcade
     password: $6$eK09oKpkO3J$hSDmoqY8WJX5pbMYNcQ7/p8LNR8p.18vhaoIYwc9uhcbOKuYPK10P6oCSNRTp/Cd8YiSwte9VB32GyVhkPLWV.
     shell: /bin/bash
     createhome: no
     groups: adm,cdrom,dip,plugdev,sudo
  when: ansible_distribution == 'Ubuntu'

- name: Arcade user doesn't need password for sudo
  blockinfile:
    create: yes
    dest: "/etc/sudoers"
    marker: "#Arcade user passwordless"
    block: |
      arcade ALL=(ALL) NOPASSWD: ALL

- name: Remove the user 'user'
  user:
    name: user
    state: absent
    remove: yes

- name: Autologin with user arcade
  lineinfile:
    dest: /etc/lightdm/lightdm.conf.d/lightdm-autologin-greeter.conf 
    regexp: 'autologin-user=user'
    line: 'autologin-user=arcade'
    backrefs: yes

- name: Copy new whiskermenu
  copy:
    src: "{{ role_path }}/files/etc/xdg/xfce4/panel/whiskermenu-1.rc"
    dest: /etc/xdg/xfce4/panel/whiskermenu-1.rc
    mode: 0644

- name: New panel configuration
  copy:
    src: "{{ role_path }}/files/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml"
    dest: /etc/xdg/xfce4/panel/xfce4-panel.xml
    mode: 0644

- name: New panel configuration2
  copy:
    src: "{{ role_path }}/files/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml"
    dest: /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml
    mode: 0644

- name: Disable compositing
  copy:
    src: "{{ role_path }}/files/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml"
    dest: /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml
    mode: 0644

- name: New keyboard shortcuts
  copy:
    src: "{{ role_path }}/files/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml"
    dest: /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml
    mode: 0644

- name: Set Firefox policies in Debian.
  copy:
    src: "{{ role_path }}/files/usr/share/firefox-esr/distribution/policies.json"
    dest: "/usr/share/firefox-esr/distribution/policies.json"
    mode: 0644
  when: ansible_distribution == 'Debian'

- name: Set Firefox policies in Ubuntu.
  copy:
    src: "{{ role_path }}/files/usr/share/firefox-esr/distribution/policies.json"
    dest: "/usr/lib/firefox/distribution/policies.json"
    mode: 0644
  when: ansible_distribution == 'Ubuntu'
