- name: jaitsi git
  git:
    repo: 'https://github.com/dolphin-emu/dolphin'
    dest: /root/dolphin

- name: Build-depends
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - debhelper
    - debhelper
    - cmake
    - dpkg-dev
    - gettext
    - libao-dev
    - libasound2-dev
    - libavcodec-dev
    - libavformat-dev
    - libavutil-dev
    - libbluetooth-dev
    - libcurl4-gnutls-dev
    - libenet-dev
    - libevdev-dev
    - libgl1-mesa-dev
    - libgtest-dev
    - libgtk2.0-dev
    - liblzo2-dev
    - libmbedtls-dev
    - libminiupnpc-dev
    - libopenal-dev
    - libpng-dev
    - libpulse-dev
    - libsfml-dev
    - libsoil-dev
    - libsoundtouch-dev
    - libswscale-dev
    - libwxgtk3.0-dev
    - libx11-dev
    - libxi-dev
    - libxrandr-dev
    - libudev-dev
    - libusb-1.0-0-dev
    - lsb-release
    - pkg-config
    - portaudio19-dev
    - zlib1g-dev
    - qtbase5-private-dev

- name: ziurtatu build karpeta existitzen dela
  file:
    path: "/root/dolphin/build"
    state: directory

- name: Configure
  command: "cmake .."
  args:
    chdir: "/root/dolphin/build"

- name: Build
  make:
    chdir: /root/dolphin/build
    params:
      NUM_THREADS: 4

- name: Build install
  make:
    chdir: /root/dolphin/build
    target: install

