#this task configures the dns server
---
- name: Set hostname
  hostname:
    name: DC1

- name: Ensure resolv.conf is not immutable.
  file:
    path: /etc/resolv.conf
    attr: -i

- name: Remove original resolv.conf.
  file:
    path="/etc/resolv.conf"
    state=absent

- name: Create new resolv.conf.
  blockinfile:
    dest: "/etc/resolv.conf"
    create: "true"
    block: |
     domain mydomain.org
     search mydomain.org
     nameserver 127.0.0.1

- name: Ensure resolv.conf is immutable.
  file:
    path: /etc/resolv.conf
    attr: +i
  register: resolv_file
  changed_when: "'i' not in resolv_file.diff.before.attributes"
