#This task configures the domain
---
- name: Remove original samba configuration.
  file:
    path="/etc/samba/smb.conf"
    state=absent

- name: Configure domain.
  ansible.builtin.command:
    argv:
      - /usr/bin/samba-tool
      - domain
      - provision
      - --server-role=dc
#      - --use-rfc2307
      - --dns-backend=SAMBA_INTERNAL
      - --realm=MYDOMAIN.ORG
      - --domain=MYDOMAIN
      - --adminpass=DomainPass2

- name: Copy kerberos configuration.
  copy:
    src: "/var/lib/samba/private/krb5.conf"
    dest: "/etc/krb5.conf"
    mode: 0600

- name: Stop smbd service.
  service:
    name: smbd
    state: stopped

- name: Stop nmbd service.
  service:
    name: nmbd
    state: stopped

- name: Stop winbind service.
  service:
    name: winbind
    state: stopped

- name: Restart samba service.
  service:
    name: samba
    state: restarted
