#this task will set up Samba as an Active Directory Domain Controller
#https://wiki.samba.org/index.php/Setting_up_Samba_as_an_Active_Directory_Domain_Controller#Provisioning_Samba_AD_in_Non-interactive_Mode
#https://samba.tranquil.it/doc/en/samba_config_server/debian/server_install_samba_debian.html
---
- name: Set hostname
  hostname:
    name: DC1

#https://stackoverflow.com/questions/51784208/stop-network-manager-from-updating-resolv-conf
- name: Install dependencies.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
     - samba
     - krb5-user
     - krb5-config
     - winbind
     - smbclient
     - libpam-winbind
     - libnss-winbind

- name: Remove original samba configuration.
  file:
    path="/etc/samba/smb.conf"
    state=absent

- name: Configure domain.
  ansible.builtin.command:
    argv:
      - /usr/bin/samba-tool
      - domain
      - provision
      - --server-role=dc
#      - --use-rfc2307
      - --dns-backend=SAMBA_INTERNAL
      - --realm=PROBA.ORG
      - --domain=PROBA
      - --adminpass=Hauprobada2

- name: Copy kerberos configuration.
  copy:
    src: "/var/lib/samba/private/krb5.conf"
    dest: "/etc/krb5.conf"
    mode: 0600

- name: Remove original resolv.conf.
  file:
    path="/etc/resolv.conf"
    state=absent

- name: Create new resolv.conf.
  blockinfile:
    dest: "/etc/resolv.conf"
    create: "true"
    block: |
     domain proba.org
     search proba.org
     nameserver 127.0.0.1

- name: Ensure resolv.conf is immutable.
  file:
    path: /etc/resolv.conf
    attr: +i
  register: resolv_file
  changed_when: "'i' not in resolv_file.diff.before.attributes"

- name: Stop services.
  service:
    name: "{{ services }}"
    state: stopped
  vars:
    services:
    - smbd
    - nmbd
    - winbind
    - samba

- name: Start samba service.
  service:
    name: samba
    state: started
