#this task will set up Samba as an Active Directory Domain Controller
#https://wiki.samba.org/index.php/Setting_up_Samba_as_an_Active_Directory_Domain_Controller#Provisioning_Samba_AD_in_Non-interactive_Mode
---
- name: Install dependencies.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
     - samba
#     - krb5-user
#     - krb5-config
#     - winbind
#     - smbclient
#     - libpam-winbind
#     - libnss-winbind

- name: Remove original samba configuration.
  file:
    path="/etc/samba/smb.conf"
    state=absent

- name: Configure domain.
  ansible.builtin.command:
    argv:
      - /usr/bin/samba-tool
      - domain
      - provision
      - --server-role=dc
#      - --use-rfc2307
      - --dns-backend=SAMBA_INTERNAL
      - --realm=PROBA.ORG
      - --domain=PROBA
      - --adminpass=Hauprobada2

- name: Copy kerberos configuration.
  copy:
    src: "/var/lib/samba/private/krb5.conf"
    dest: "/etc/krb5.conf"
    mode: 0600
