#this task installs wayfire and some extra tools
---
- name: Install wayfire and extras.
  apt:
    name: "{{ packages }}"
    install_recommends: yes
  vars:
    packages:
    - wayfire
    - libgl1-mesa-dri
    - kanshi
    - mako-notifier
    - wlsunset
    - swayidle
    - swaylock
    - xdg-desktop-portal
    - alacritty
    - wlogout
    - wofi
    - grim
    - slurp
    - alsa-utils
    - light

- name: Install wf-shell.
  apt:
    name: "{{ packages }}"
    install_recommends: yes
  vars:
    packages:
    - wf-shell
  when: ansible_distribution == 'Ubuntu'

- name: Create config files in skel.
  file:
    path: "/etc/skel/.config"
    state: directory
    mode: 0755

- name: Create config dirs in skel.
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "/etc/skel/.config"
    - "/etc/skel/.config/wofi"

- name: Copy wayfire config file to skel.
  copy:
    src: "/usr/share/doc/wayfire/examples/wayfire.ini"
    dest: "/etc/skel/.config/wayfire.ini"
    mode: 0644
    remote_src: yes

- name: Configure wofi.
  ansible.builtin.blockinfile:
    path: "/etc/skel/.config/wofi/config"
    create: yes
    block: |
      mode=drun

- name: Set spanish keyboard.
  replace:
    dest: "/etc/skel/.config/wayfire.ini"
    regexp: "{{ item.old }}"
    replace: "{{ item.new }}"
  with_items:
     - { old: "# \\[input\\]", new: "[input]" }
     - { old: "# xkb_layout = us,fr", new: "xkb_layout = es" }
